packages:
  - apps/admin/api
  - apps/admin/web
  - packages/tsconfig
  - packages/ui
  - packages/auth
  - apps/s3-browser/api
  - apps/s3-browser/web

onlyBuiltDependencies:
  - bcrypt
  - esbuild
  - sqlite3
