apiVersion: v1
kind: Secret
metadata:
  name: {{ include "garage-admin-console.serviceAccountName" . }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.env.jwtSecret | b64enc | quote }}
  ENCRYPTION_KEY: {{ .Values.env.encryptionKey | b64enc | quote }}
  ADMIN_PASSWORD: {{ .Values.env.adminPassword | b64enc | quote }}