// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from 'path';
import { defineConfig } from 'prisma/config';

const dbPath = path.resolve(process.cwd(), 'data.db');
const dbUrl = `file:${dbPath}`;

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: dbUrl,
  },
});
